<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Guide</title>
    <link rel="stylesheet" href="./css/style.css">
</head>
<body class="help-body">

<div class="help-container">
    <h1 class="help-title">Ocean View Resort - User Guide</h1>

    <div class="help-section">
        <h2>1. System Login</h2>
        <p>Access the management dashboard securely by entering your authorized credentials.</p>
        <ul>
            <li>Enter your unique <strong>Username</strong>.</li>
            <li>Enter your <strong>Password</strong>.</li>
            <li>Click the <strong>Login</strong> button to proceed to the dashboard.</li>
        </ul>
        <div class="alert-box">
            <strong>Note:</strong> If you enter incorrect credentials, the system will display an error message. Ensure your caps lock is off.
        </div>
        <div class="img-wrapper">
            <img src="images/loginPage.png" alt="Login Page View" class="help-img" onerror="this.style.display='none'">
        </div>
    </div>

    <div class="help-section">
        <h2>2. Register a New Reservation</h2>
        <p>Follow these steps to book a room for a new guest in the system.</p>
        <ul>
            <li>Navigate to the <strong>Add Reservation</strong> section from the sidebar.</li>
            <li>The <strong>Reservation Number</strong> is auto-generated by the database.</li>
            <li>Input the Guest Name, Residential Address, and Contact Number.</li>
            <li>Select the preferred <strong>Room Type</strong> (Standard, Deluxe, or Suite).</li>
            <li>Select the Check-in and Check-out dates using the calendar picker.</li>
            <li>Click <strong>Submit</strong> to save the booking.</li>
        </ul>
        <div class="img-wrapper">
            <img src="images/addReservation.png" alt="Reservation Entry Form" class="help-img" onerror="this.style.display='none'">
        </div>
    </div>

    <div class="help-section">
        <h2>3. Manage & Update Reservations</h2>
        <p>Review current bookings or modify guest information as needed.</p>
        <ul>
            <li>Go to <strong>View Reservations</strong> to see the complete list of guests.</li>
            <li>Click the <strong>Edit</strong> button next to a row to open the update form.</li>
            <li>Modify fields such as dates or room type and click <strong>Update</strong>.</li>
            <li>Use the <strong>Delete</strong> button to remove a cancelled booking permanently.</li>
        </ul>
        <div class="img-wrapper">
            <img src="images/viewReservations.png" alt="View List" class="help-img" onerror="this.style.display='none'" style="margin-bottom: 10px;">
            <img src="images/updateReservation.png" alt="Update Form" class="help-img" onerror="this.style.display='none'">
        </div>
    </div>

    <div class="help-section">
        <h2>4. Billing and Invoices</h2>
        <p>Calculate final stay costs and provide guests with a printed invoice.</p>
        <ul>
            <li>Select <strong>Calculate Bill</strong> from the sidebar menu.</li>
            <li>Search for or choose the <strong>Reservation No</strong> from the dropdown list.</li>
            <li>The system automatically calculates the total based on room rates and duration (nights stayed).</li>
            <li>Click <strong>Print Invoice</strong> to generate a physical copy for the guest.</li>
        </ul>
        <div class="img-wrapper">
            <img src="images/calculateBill.png" alt="Calculation Interface" class="help-img" onerror="this.style.display='none'" style="margin-bottom: 10px;">
            <img src="images/printBill.png" alt="Invoice Preview" class="help-img" onerror="this.style.display='none'">
        </div>
    </div>

</div>

</body>
</html>